# Generated by Django 2.2 on 2020-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeitem',
            name='parent_resume_id',
            field=models.PositiveIntegerField(default=-1),
        ),
    ]
